"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendSystemEmail } from "@/lib/email";
import { archiveToGoogleDrive } from "@/lib/google-drive";

function v(fd:FormData,k:string){return String(fd.get(k)||"").trim()}
async function me(){const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect('/login');const {data:p}=await s.from('profiles').select('id,full_name,email,app_role,manager_id,job_title').eq('id',user.id).single();if(!p)throw new Error('Profile not found');return p}
async function log(id:string,type:string,recipients:string[],r:any){const a=createAdminClient();await a.from('timesheet_notification_log').insert({timesheet_id:id,event_type:type,recipients,delivery_status:r.status,provider_message_id:r.id,error_message:r.error})}


function csvCell(value: unknown) { return `"${String(value ?? "").replaceAll('"','""')}"`; }
async function timesheetCsv(admin: ReturnType<typeof createAdminClient>, t: any) {
  const start = `${t.timesheet_year}-${String(t.timesheet_month).padStart(2,'0')}-01`;
  const endDate = new Date(Date.UTC(t.timesheet_year, t.timesheet_month, 0));
  const end = endDate.toISOString().slice(0,10);
  const [assignR, holidayR, leaveR, overtimeR] = await Promise.all([
    admin.from('rota_assignments').select('work_date,status_code,shift_start,shift_end,note').eq('employee_id',t.employee_id).gte('work_date',start).lte('work_date',end),
    admin.from('holidays').select('holiday_date,name').eq('active',true).gte('holiday_date',start).lte('holiday_date',end),
    admin.from('leave_requests').select('start_date,end_date,leave_types(name,code)').eq('employee_id',t.employee_id).eq('status','approved').lte('start_date',end).gte('end_date',start),
    admin.from('overtime_requests').select('overtime_date,requested_hours').eq('employee_id',t.employee_id).eq('status','approved').gte('overtime_date',start).lte('overtime_date',end),
  ]);
  const assignments=assignR.data||[], holidays=holidayR.data||[], leaves=leaveR.data||[], overtime=overtimeR.data||[];
  const lines = [
    ['Employee', t.employee?.full_name || 'Employee'], ['Employee ID', t.employee?.employee_no || ''], ['Year', t.timesheet_year], ['Month', t.timesheet_month], [],
    ['Date','Day','Status','Details','Shift Start','Shift End','Overtime Hours'].map(csvCell).join(',')
  ];
  for(let day=1; day<=endDate.getUTCDate(); day++){
    const date=`${t.timesheet_year}-${String(t.timesheet_month).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
    const leave:any=leaves.find((x:any)=>x.start_date<=date&&x.end_date>=date); const holiday:any=holidays.find((x:any)=>x.holiday_date===date); const assignment:any=assignments.find((x:any)=>x.work_date===date);
    const weekend=[5,6].includes(new Date(date+'T00:00:00Z').getUTCDay());
    const code=leave?(leave.leave_types?.code||'LV'):assignment?.status_code||(holiday&&!weekend?'PH':(weekend?'OFF':'ON'));
    const detail=leave?(leave.leave_types?.name||'Leave'):assignment?.note||(holiday&&!weekend?holiday.name:(weekend?'Weekend':'Working'));
    const ot=overtime.filter((x:any)=>x.overtime_date===date).reduce((n:number,x:any)=>n+Number(x.requested_hours||0),0);
    lines.push([date,new Date(date+'T00:00:00Z').toLocaleDateString('en-GB',{weekday:'long',timeZone:'UTC'}),code,detail,assignment?.shift_start||'',assignment?.shift_end||'',ot].map(csvCell).join(','));
  }
  return lines.map((x:any)=>Array.isArray(x)?x.map(csvCell).join(','):x).join('\r\n');
}
export async function submitTimesheet(fd:FormData){const p=await me();const year=Number(v(fd,'year'));const month=Number(v(fd,'month'));const a=createAdminClient();const {data:t,error}=await a.from('timesheets').upsert({employee_id:p.id,timesheet_year:year,timesheet_month:month,status:'submitted',manager_id:p.manager_id,submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'employee_id,timesheet_year,timesheet_month'}).select('id').single();if(error||!t)throw new Error(error?.message||'Cannot submit timesheet');if(!p.manager_id)throw new Error('No line manager is assigned to your employee profile.');const {data:m}=await a.from('profiles').select('full_name,email').eq('id',p.manager_id).single();if(m?.email){const r=await sendSystemEmail({to:[m.email],subject:`Timesheet approval required: ${p.full_name}`,idempotencyKey:`timesheet-submit-${t.id}`,html:`<h2>Timesheet approval required</h2><p>${p.full_name} submitted the timesheet for ${year}-${String(month).padStart(2,'0')}.</p><p><a href="https://teamrota-one.vercel.app/timesheets" style="display:inline-block;padding:12px 20px;background:#155ee9;color:#ffffff;text-decoration:none;border-radius:8px;font-weight:700">Open TeamRota Timesheets</a></p><p style="font-size:12px;color:#64748b">Direct link: <a href="https://teamrota-one.vercel.app/timesheets">https://teamrota-one.vercel.app/timesheets</a></p>`});await log(t.id,'submitted_manager',[m.email],r)}revalidatePath('/timesheets');revalidatePath('/dashboard')}

export async function decideTimesheet(fd:FormData){const p=await me();const id=v(fd,'timesheet_id');const decision=v(fd,'decision');if(!['approved','rejected'].includes(decision))throw new Error('Invalid decision');const a=createAdminClient();const {data:t}=await a.from('timesheets').select('*,employee:profiles!timesheets_employee_id_fkey(full_name,email)').eq('id',id).single();if(!t)throw new Error('Timesheet not found');const role=String(p.app_role||'').toLowerCase();if(!(role==='admin'||t.manager_id===p.id))throw new Error('Not authorized');const status=decision==='approved'?'manager_approved':'manager_rejected';const {error}=await a.from('timesheets').update({status,manager_decided_by:p.id,manager_decided_at:new Date().toISOString(),manager_comment:v(fd,'comment')||null,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw new Error(error.message);const employeeEmail=t.employee?.email;const hr=(process.env.HR_NOTIFICATION_EMAIL||'').trim();const recipients=decision==='approved'?[employeeEmail,hr].filter(Boolean):[employeeEmail].filter(Boolean);for(const email of recipients){const r=await sendSystemEmail({to:[email],subject:`Timesheet ${decision}: ${t.employee?.full_name||'Employee'}`,idempotencyKey:`timesheet-${decision}-${id}-${email}`,html:`<h2>Timesheet ${decision}</h2><p>The ${t.timesheet_year}-${String(t.timesheet_month).padStart(2,'0')} timesheet for ${t.employee?.full_name||'employee'} was ${decision} by ${p.full_name}.</p>`});await log(id,decision==='approved'&&email===hr?'approved_hr':`${decision}_employee`,[email],r)}revalidatePath('/timesheets');revalidatePath('/dashboard')}

export async function completeTimesheet(fd:FormData){const p=await me();const role=String(p.app_role||'').toLowerCase();const hrTitle=/\bhr\b|human\s*resources?|people\s*(?:&|and)\s*culture/i.test(String(p.job_title||''));if(!(role==='admin'||role==='hr'||hrTitle))throw new Error('HR or Admin access required');const id=v(fd,'timesheet_id');const action=v(fd,'hr_action');const a=createAdminClient();const status=action==='payroll'?'done':'hr_done';const payload:any={status,hr_completed_by:p.id,hr_completed_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(action==='payroll'){payload.payroll_sent_by=p.id;payload.payroll_sent_at=new Date().toISOString()}const {data:t,error}=await a.from('timesheets').update(payload).eq('id',id).select('*,employee:profiles!timesheets_employee_id_fkey(full_name,email,employee_no)').single();if(error||!t)throw new Error(error?.message||'Unable to update timesheet');const csv=await timesheetCsv(a,t);const month=String(t.timesheet_month).padStart(2,'0');const archiveType=action==='payroll'?'payroll_timesheet':'timesheet';const folders=action==='payroll'?['TeamRota Documents','Payroll',String(t.timesheet_year),month]:['TeamRota Documents','Employees',`${t.employee?.full_name||'Employee'} (${t.employee_id})`,'Timesheets',String(t.timesheet_year)];await archiveToGoogleDrive({entityType:archiveType,entityId:id,employeeId:t.employee_id,employeeName:t.employee?.full_name,year:t.timesheet_year,month:t.timesheet_month,fileName:`${t.employee?.employee_no||t.employee_id}_${t.employee?.full_name||'Employee'}_${t.timesheet_year}-${month}_${action==='payroll'?'Payroll':'Timesheet'}.csv`.replace(/[^a-zA-Z0-9._-]+/g,'_'),mimeType:'text/csv',data:csv,folders,archivedBy:p.id,metadata:{status,action}}).catch((e)=>console.error('Timesheet archive failed:',e));if(action==='payroll'){const payroll=(process.env.PAYROLL_NOTIFICATION_EMAIL||'').trim();if(payroll){const r=await sendSystemEmail({to:[payroll],subject:`Payroll timesheet: ${t.employee?.full_name}`,idempotencyKey:`timesheet-payroll-${id}`,html:`<h2>Approved payroll timesheet</h2><p>${t.employee?.full_name} — ${t.timesheet_year}-${month}.</p><p>The finalized record has also been archived in Google Drive.</p>`});await log(id,'sent_payroll',[payroll],r)}}revalidatePath('/timesheets');revalidatePath('/dashboard');revalidatePath('/admin/storage')}
