"use client";

import { useEffect, useState } from "react";

type Language = "en" | "ku" | "ar" | "ur";

const ku: Record<string, string> = {
  "Dashboard": "داشبۆرد",
  "Organization Chart": "هێڵکاری ڕێکخراو",
  "Employee Directory": "بەڵگەنامەی کارمەندان",
  "People & Structure": "خەڵک و پێکهاتە",
  "Rota Planner": "پلاندانەری ڕۆتا",
  "Annual Rota": "ڕۆتای ساڵانە",
  "Holiday Calendar": "ڕۆژژمێری پشوو",
  "Leave & Balances": "مۆڵەت و باڵانسەکان",
  "Overtime": "کاتی زیادە",
  "Timesheets": "خشتەی کات",
  "My Profile & Settings": "پرۆفایل و ڕێکخستنەکانم",
  "Admin Workspace": "شوێنی کاری ئەدمین",
  "Holiday Settings": "ڕێکخستنەکانی پشوو",
  "Email Diagnostics": "پشکنینی ئیمەیڵ",
  "Sign out": "چوونەدەرەوە",
  "ORGANIZATION": "ڕێکخراو",
  "WORKFORCE": "هێزی کار",
  "ADMINISTRATION": "بەڕێوەبردن",
  "Leave": "مۆڵەت",
  "LEAVE": "مۆڵەت",
  "Request Leave": "داواکاری مۆڵەت",
  "Leave History": "مێژووی مۆڵەت",
  "Pending My Approval": "چاوەڕوانی پەسەندکردنی من",
  "Approve": "پەسەندکردن",
  "Reject": "ڕەتکردنەوە",
  "Amend decision": "گۆڕینی بڕیار",
  "Change to approved": "گۆڕین بۆ پەسەندکراو",
  "Change to rejected": "گۆڕین بۆ ڕەتکراوە",
  "Amendment reason": "هۆکاری گۆڕین",
  "Submit request": "ناردنی داواکاری",
  "Supporting document": "بەڵگەی پشتگیری",
  "Open supporting document": "کردنەوەی بەڵگەی پشتگیری",
  "View document": "بینینی بەڵگە",
  "Decision comment": "تێبینی بڕیار",
  "Reason / justification": "هۆکار / پاساو",
  "Leave type *": "جۆری مۆڵەت *",
  "Entitled": "مافی هەیە",
  "Used": "بەکارهاتوو",
  "Remaining": "ماوە",
  "Carry-forward": "گواستنەوە",
  "Configured": "ڕێکخراوە",
  "Not configured": "ڕێکنەخراوە",
  "Provider": "دابینکەر",
  "Sender": "نێرەر",
  "Notification Diagnostics": "پشکنینی ئاگادارکردنەوە",
  "Leave notifications": "ئاگادارکردنەوەکانی مۆڵەت",
  "Overtime notifications": "ئاگادارکردنەوەکانی کاتی زیادە",
  "No notification records found.": "هیچ تۆماری ئاگادارکردنەوەیەک نەدۆزرایەوە.",
  "Workforce Rota Planner": "پلاندانەری ڕۆتای هێزی کار",
  "Start date": "بەرواری دەستپێک",
  "Number of days": "ژمارەی ڕۆژەکان",
  "Employee": "کارمەند",
  "View rota": "بینینی ڕۆتا",
  "Print / Save PDF": "چاپ / پاشەکەوتکردنی PDF",
  "Visible employees": "کارمەندانی دیار",
  "Active rotations": "ڕۆتاکانی چالاک",
  "Manual assignments": "دانانە دەستییەکان",
  "Create Rotation Pattern": "دروستکردنی شێوازی ڕۆتا",
  "Assign Employee Rotation": "دانانی ڕۆتا بۆ کارمەند",
  "Manual Rota Override": "گۆڕینی دەستی ڕۆتا",
  "Save": "پاشەکەوتکردن",
  "Create": "دروستکردن",
  "Assign": "دانان",
  "ON – Day": "کار – ڕۆژ",
  "ON – Night": "کار – شەو",
  "OFF – Rest": "پشوو",
  "Public Holiday": "پشووی فەرمی",
  "Annual Leave": "مۆڵەتی ساڵانە",
  "Sick Leave": "مۆڵەتی نەخۆشی",
  "Maternity Leave": "مۆڵەتی دایکایەتی",
  "Marriage Leave": "مۆڵەتی هاوسەرگیری",
  "Unpaid Leave": "مۆڵەتی بێ مووچە",
  "Remote": "کار لە دوورەوە",
  "Travel": "گەشت",
  "Training": "ڕاهێنان",
  "Annual Rota Planner": "پلاندانەری ڕۆتای ساڵانە",
  "Total Year Rota": "کۆی ڕۆتای ساڵ",
  "View": "بینین",
  "January": "کانوونی دووەم",
  "February": "شوبات",
  "March": "ئازار",
  "April": "نیسان",
  "May": "ئایار",
  "June": "حوزەیران",
  "July": "تەمموز",
  "August": "ئاب",
  "September": "ئەیلوول",
  "October": "تشرینی یەکەم",
  "November": "تشرینی دووەم",
  "December": "کانوونی یەکەم",
  "Employees": "کارمەندان",
  "Active Employees": "کارمەندانی چالاک",
  "On Duty Today": "ئەمڕۆ لە کاردان",
  "On Leave Today": "ئەمڕۆ لە مۆڵەتدان",
  "Pending Requests": "داواکارییە چاوەڕوانەکان",
  "Pending Leave": "مۆڵەتی چاوەڕوان",
  "Departments": "بەشەکان",
  "Rota Entries Today": "تۆمارەکانی ڕۆتای ئەمڕۆ",
  "Pending Overtime": "کاتی زیادەی چاوەڕوان",
  "Organization Overview": "پوختەی ڕێکخراو",
  "Next Holiday": "پشووی داهاتوو",
  "Open calendar": "کردنەوەی ڕۆژژمێر",
  "Manage": "بەڕێوەبردن",
  "My Timesheets": "خشتە کاتەکانم",
  "Monthly Timesheets": "خشتە کاتی مانگانە",
  "Submit to manager": "ناردن بۆ بەڕێوەبەر",
  "Send to Payroll": "ناردن بۆ مووچە",
  "Mark Done": "نیشانکردن وەک تەواو",
  "Print": "چاپ",
  "Employee ID": "ژمارەی کارمەند",
  "Join date": "بەرواری دەستبەکاربوون",
  "Line Manager": "بەڕێوەبەری ڕاستەوخۆ",
  "Leave approver": "پەسەندکەری مۆڵەت",
  "Status": "دۆخ",
  "Date": "بەروار",
  "Day": "ڕۆژ",
  "Month": "مانگ",
  "Year": "ساڵ",
  "Shift": "شێفت",
  "Details": "وردەکاری",
  "Hours": "کاتژمێر",
  "Email address": "ناونیشانی ئیمەیڵ",
  "Password": "وشەی نهێنی",
  "Sign in": "چوونەژوورەوە",
  "Forgot password?": "وشەی نهێنیت لەبیرچووە؟",
  "Reset password": "نوێکردنەوەی وشەی نهێنی",
  "Temporary password": "وشەی نهێنی کاتی",
  "Set temporary password": "دانانی وشەی نهێنی کاتی",
  "Settings": "ڕێکخستنەکان",
  "Profile": "پرۆفایل",
  "Phone": "ژمارەی تەلەفۆن",
  "Job title": "ناونیشانی کار",
  "Gender": "ڕەگەز",
  "Male": "نێر",
  "Female": "مێ",
  "Create Employee Account": "دروستکردنی هەژماری کارمەند",
  "Create employee": "دروستکردنی کارمەند",
  "Secondary Reporting Lines": "هێڵەکانی ڕاپۆرتی دووەم",
  "Dotted-line manager": "بەڕێوەبەری هێڵی خاڵدار",
  "Reporting label": "ناونیشانی ڕاپۆرت",
  "Add dotted line": "زیادکردنی هێڵی خاڵدار",
  "Remove": "لابردن",
  "English": "English",
  "Kurdish (Sorani)": "کوردی (سۆرانی)",
  "Arabic": "العربية"
};

const ar: Record<string, string> = {
  "Dashboard": "لوحة التحكم",
  "Organization Chart": "الهيكل التنظيمي",
  "Employee Directory": "دليل الموظفين",
  "People & Structure": "الأفراد والهيكل",
  "Rota Planner": "مخطط المناوبات",
  "Annual Rota": "المناوبات السنوية",
  "Holiday Calendar": "تقويم العطل",
  "Leave & Balances": "الإجازات والأرصدة",
  "Overtime": "العمل الإضافي",
  "Timesheets": "سجلات الدوام",
  "My Profile & Settings": "ملفي وإعداداتي",
  "Admin Workspace": "مساحة الإدارة",
  "Holiday Settings": "إعدادات العطل",
  "Email Diagnostics": "تشخيص البريد الإلكتروني",
  "Sign out": "تسجيل الخروج",
  "ORGANIZATION": "المنظمة",
  "WORKFORCE": "القوى العاملة",
  "ADMINISTRATION": "الإدارة",
  "Leave": "إجازة",
  "LEAVE": "الإجازات",
  "Request Leave": "طلب إجازة",
  "Leave History": "سجل الإجازات",
  "Pending My Approval": "بانتظار موافقتي",
  "Approve": "موافقة",
  "Reject": "رفض",
  "Amend decision": "تعديل القرار",
  "Change to approved": "تغيير إلى موافق عليه",
  "Change to rejected": "تغيير إلى مرفوض",
  "Amendment reason": "سبب التعديل",
  "Submit request": "إرسال الطلب",
  "Supporting document": "المستند الداعم",
  "Open supporting document": "فتح المستند الداعم",
  "View document": "عرض المستند",
  "Decision comment": "ملاحظة القرار",
  "Reason / justification": "السبب / التبرير",
  "Leave type *": "نوع الإجازة *",
  "Entitled": "الاستحقاق",
  "Used": "المستخدم",
  "Remaining": "المتبقي",
  "Carry-forward": "المرحل",
  "Configured": "مُعد",
  "Not configured": "غير مُعد",
  "Provider": "المزود",
  "Sender": "المرسل",
  "Notification Diagnostics": "تشخيص الإشعارات",
  "Leave notifications": "إشعارات الإجازات",
  "Overtime notifications": "إشعارات العمل الإضافي",
  "No notification records found.": "لم يتم العثور على سجلات إشعارات.",
  "Workforce Rota Planner": "مخطط مناوبات القوى العاملة",
  "Start date": "تاريخ البدء",
  "Number of days": "عدد الأيام",
  "Employee": "الموظف",
  "View rota": "عرض المناوبة",
  "Print / Save PDF": "طباعة / حفظ PDF",
  "Visible employees": "الموظفون الظاهرون",
  "Active rotations": "المناوبات النشطة",
  "Manual assignments": "التعيينات اليدوية",
  "Create Rotation Pattern": "إنشاء نمط مناوبة",
  "Assign Employee Rotation": "تعيين مناوبة للموظف",
  "Manual Rota Override": "تعديل المناوبة يدوياً",
  "Save": "حفظ",
  "Create": "إنشاء",
  "Assign": "تعيين",
  "ON – Day": "دوام نهاري",
  "ON – Night": "دوام ليلي",
  "OFF – Rest": "راحة",
  "Public Holiday": "عطلة رسمية",
  "Annual Leave": "إجازة سنوية",
  "Sick Leave": "إجازة مرضية",
  "Maternity Leave": "إجازة أمومة",
  "Marriage Leave": "إجازة زواج",
  "Unpaid Leave": "إجازة بدون راتب",
  "Remote": "عمل عن بُعد",
  "Travel": "سفر",
  "Training": "تدريب",
  "Annual Rota Planner": "مخطط المناوبات السنوي",
  "Total Year Rota": "إجمالي مناوبات السنة",
  "View": "عرض",
  "January": "يناير",
  "February": "فبراير",
  "March": "مارس",
  "April": "أبريل",
  "May": "مايو",
  "June": "يونيو",
  "July": "يوليو",
  "August": "أغسطس",
  "September": "سبتمبر",
  "October": "أكتوبر",
  "November": "نوفمبر",
  "December": "ديسمبر",
  "Employees": "الموظفون",
  "Active Employees": "الموظفون النشطون",
  "On Duty Today": "على رأس العمل اليوم",
  "On Leave Today": "في إجازة اليوم",
  "Pending Requests": "الطلبات المعلقة",
  "Pending Leave": "الإجازات المعلقة",
  "Departments": "الأقسام",
  "Rota Entries Today": "سجلات مناوبة اليوم",
  "Pending Overtime": "العمل الإضافي المعلق",
  "Organization Overview": "نظرة عامة على المنظمة",
  "Next Holiday": "العطلة القادمة",
  "Open calendar": "فتح التقويم",
  "Manage": "إدارة",
  "My Timesheets": "سجلات دوامي",
  "Monthly Timesheets": "سجلات الدوام الشهرية",
  "Submit to manager": "إرسال إلى المدير",
  "Send to Payroll": "إرسال إلى الرواتب",
  "Mark Done": "وضع علامة مكتمل",
  "Print": "طباعة",
  "Employee ID": "رقم الموظف",
  "Join date": "تاريخ الالتحاق",
  "Line Manager": "المدير المباشر",
  "Leave approver": "معتمد الإجازة",
  "Status": "الحالة",
  "Date": "التاريخ",
  "Day": "اليوم",
  "Month": "الشهر",
  "Year": "السنة",
  "Shift": "الوردية",
  "Details": "التفاصيل",
  "Hours": "الساعات",
  "Email address": "عنوان البريد الإلكتروني",
  "Password": "كلمة المرور",
  "Sign in": "تسجيل الدخول",
  "Forgot password?": "هل نسيت كلمة المرور؟",
  "Reset password": "إعادة تعيين كلمة المرور",
  "Temporary password": "كلمة مرور مؤقتة",
  "Set temporary password": "تعيين كلمة مرور مؤقتة",
  "Settings": "الإعدادات",
  "Profile": "الملف الشخصي",
  "Phone": "الهاتف",
  "Job title": "المسمى الوظيفي",
  "Gender": "الجنس",
  "Male": "ذكر",
  "Female": "أنثى",
  "Create Employee Account": "إنشاء حساب موظف",
  "Create employee": "إنشاء موظف",
  "Secondary Reporting Lines": "خطوط التقارير الثانوية",
  "Dotted-line manager": "مدير الخط المنقط",
  "Reporting label": "وصف خط التقرير",
  "Add dotted line": "إضافة خط منقط",
  "Remove": "إزالة",
  "English": "English",
  "Kurdish (Sorani)": "کوردی",
  "Arabic": "العربية",
  "Urdu": "اردو"
};

const ur: Record<string, string> = {
  "Dashboard": "ڈیش بورڈ",
  "Organization Chart": "تنظیمی چارٹ",
  "Employee Directory": "ملازمین کی فہرست",
  "People & Structure": "افراد اور تنظیم",
  "Rota Planner": "روٹا پلانر",
  "Annual Rota": "سالانہ روٹا",
  "Holiday Calendar": "تعطیلات کا کیلنڈر",
  "Leave & Balances": "چھٹیاں اور بیلنس",
  "Overtime": "اوور ٹائم",
  "Timesheets": "ٹائم شیٹس",
  "My Profile & Settings": "میرا پروفائل اور سیٹنگز",
  "Admin Workspace": "ایڈمن ورک اسپیس",
  "Holiday Settings": "تعطیلات کی سیٹنگز",
  "Email Diagnostics": "ای میل تشخیص",
  "Sign out": "سائن آؤٹ",
  "ORGANIZATION": "تنظیم",
  "WORKFORCE": "افرادی قوت",
  "ADMINISTRATION": "انتظامیہ",
  "Leave": "چھٹی",
  "LEAVE": "چھٹی",
  "Request Leave": "چھٹی کی درخواست",
  "Leave History": "چھٹی کی تاریخ",
  "Pending My Approval": "میری منظوری کے منتظر",
  "Approve": "منظور کریں",
  "Reject": "مسترد کریں",
  "Submit request": "درخواست جمع کریں",
  "Supporting document": "معاون دستاویز",
  "Reason / justification": "وجہ / جواز",
  "Leave type *": "چھٹی کی قسم *",
  "Entitled": "استحقاق",
  "Used": "استعمال شدہ",
  "Remaining": "باقی",
  "Workforce Rota Planner": "افرادی قوت روٹا پلانر",
  "Start date": "شروع کی تاریخ",
  "Number of days": "دنوں کی تعداد",
  "Employee": "ملازم",
  "View rota": "روٹا دیکھیں",
  "Print / Save PDF": "پرنٹ / PDF محفوظ کریں",
  "Visible employees": "نظر آنے والے ملازمین",
  "Active rotations": "فعال روٹیشنز",
  "Manual assignments": "دستی اسائنمنٹس",
  "Save": "محفوظ کریں",
  "Create": "بنائیں",
  "Assign": "تفویض کریں",
  "Public Holiday": "سرکاری تعطیل",
  "Annual Leave": "سالانہ چھٹی",
  "Sick Leave": "بیماری کی چھٹی",
  "Unpaid Leave": "بلا معاوضہ چھٹی",
  "Remote": "ریموٹ",
  "Travel": "سفر",
  "Training": "تربیت",
  "Employees": "ملازمین",
  "Active Employees": "فعال ملازمین",
  "On Duty Today": "آج ڈیوٹی پر",
  "On Leave Today": "آج چھٹی پر",
  "Pending Leave": "زیر التوا چھٹی",
  "Departments": "محکمے",
  "Pending Overtime": "زیر التوا اوور ٹائم",
  "Next Holiday": "اگلی تعطیل",
  "My Timesheets": "میری ٹائم شیٹس",
  "Monthly Timesheets": "ماہانہ ٹائم شیٹس",
  "Submit to manager": "منیجر کو جمع کریں",
  "Send to Payroll": "پے رول کو بھیجیں",
  "Mark Done": "مکمل نشان زد کریں",
  "Print": "پرنٹ",
  "Employee ID": "ملازم نمبر",
  "Join date": "شمولیت کی تاریخ",
  "Line Manager": "لائن منیجر",
  "Status": "حالت",
  "Date": "تاریخ",
  "Day": "دن",
  "Month": "مہینہ",
  "Year": "سال",
  "Details": "تفصیلات",
  "Hours": "گھنٹے",
  "Email address": "ای میل ایڈریس",
  "Password": "پاس ورڈ",
  "Sign in": "سائن ان",
  "Forgot password?": "پاس ورڈ بھول گئے؟",
  "Reset password": "پاس ورڈ ری سیٹ کریں",
  "Settings": "سیٹنگز",
  "Profile": "پروفائل",
  "Phone": "فون",
  "Job title": "عہدہ",
  "Gender": "جنس",
  "Male": "مرد",
  "Female": "خاتون",
  "English": "English",
  "Kurdish (Sorani)": "کوردی",
  "Arabic": "العربية",
  "Urdu": "اردو"
};



const supplementalKu: Record<string, string> = {
  "Who Is Available Today?": "ئەمڕۆ کێ بەردەستە؟",
  "All employees can view today’s workforce availability without seeing confidential leave reasons.": "هەموو کارمەندان دەتوانن بەردەستی هێزی کاری ئەمڕۆ ببینن، بەبێ بینینی هۆکارە نهێنییەکانی مۆڵەت.",
  "Total employees": "کۆی کارمەندان",
  "Available today": "ئەمڕۆ بەردەست",
  "Not available": "بەردەست نییە",
  "Available": "بەردەست",
  "Unavailable": "بەردەست نییە",
  "Working – Day": "کار – ڕۆژ",
  "Working - Day": "کار – ڕۆژ",
  "Working": "لە کاردایە",
  "Weekend": "کۆتایی هەفتە",
  "On leave": "لە مۆڵەتدایە",
  "On Leave": "لە مۆڵەتدایە",
  "Apply filter": "جێبەجێکردنی پاڵاوتن",
  "All statuses": "هەموو دۆخەکان",
  "Search employee, ID, job title or department": "گەڕان بە ناوی کارمەند، ژمارە، ناونیشانی کار یان بەش",
  "No employees match the selected filters.": "هیچ کارمەندێک لەگەڵ پاڵاوتنە هەڵبژێردراوەکان ناگونجێت.",
  "LIVE WORKFORCE": "هێزی کاری ڕاستەوخۆ",
  "ORGANIZATION CHART": "هێڵکاری ڕێکخراو",
  "Primary reporting": "ڕاپۆرتی سەرەکی",
  "Secondary reporting": "ڕاپۆرتی دووەم",
  "Expand all": "هەمووی فراوان بکە",
  "Minimize all": "هەمووی بچووک بکە",
  "Collapse all": "هەمووی کۆبکەوە",
  "Fit to screen": "گونجاندن لەگەڵ شاشە",
  "Zoom in": "گەورەکردن",
  "Zoom out": "بچووککردن",
  "Search employees": "گەڕان بەدوای کارمەندان",
  "All departments": "هەموو بەشەکان",
  "Direct reports": "ڕاپۆرتدەرانی ڕاستەوخۆ",
  "Functional Manager": "بەڕێوەبەری فەنکشنی",
  "Department not assigned": "بەش دیاری نەکراوە",
  "No department": "بێ بەش",
  "Employee Directory": "بەڵگەنامەی کارمەندان",
  "Active": "چالاک",
  "Inactive": "ناچالاک",
  "Open": "کردنەوە",
  "Close": "داخستن",
  "Cancel": "هەڵوەشاندنەوە",
  "Delete": "سڕینەوە",
  "Edit": "دەستکاری",
  "Update": "نوێکردنەوە",
  "Activate": "چالاککردن",
  "Deactivate": "ناچالاککردن",
  "Search": "گەڕان",
  "Filter": "پاڵاوتن",
  "Clear": "پاککردنەوە",
  "Back": "گەڕانەوە",
  "Next": "دواتر",
  "Previous": "پێشتر",
  "Done": "تەواو",
  "Success": "سەرکەوتوو",
  "Error": "هەڵە",
  "Warning": "ئاگاداری",
  "Loading...": "بارکردن...",
  "No data available.": "هیچ داتایەک بەردەست نییە.",
  "No records found.": "هیچ تۆمارێک نەدۆزرایەوە.",
  "Required": "پێویستە",
  "Optional": "ئارەزوومەندانە",
  "Select employee": "کارمەند هەڵبژێرە",
  "Select department": "بەش هەڵبژێرە",
  "Select manager": "بەڕێوەبەر هەڵبژێرە",
  "Select status": "دۆخ هەڵبژێرە",
  "Select year": "ساڵ هەڵبژێرە",
  "Select month": "مانگ هەڵبژێرە",
  "From": "لە",
  "To": "بۆ",
  "Start time": "کاتی دەستپێک",
  "End time": "کاتی کۆتایی",
  "Reason": "هۆکار",
  "Notes": "تێبینییەکان",
  "Description": "وەسف",
  "Department": "بەش",
  "Manager": "بەڕێوەبەر",
  "Role": "ڕۆڵ",
  "Location": "شوێن",
  "Today": "ئەمڕۆ",
  "Tomorrow": "سبەی",
  "This month": "ئەم مانگە",
  "This year": "ئەمساڵ",
  "Pending": "چاوەڕوان",
  "Approved": "پەسەندکراو",
  "Rejected": "ڕەتکراوە",
  "Submitted": "نێردراوە",
  "Completed": "تەواوکراو",
  "Draft": "ڕەشنووس",
  "Paid": "بە مووچە",
  "Unpaid": "بێ مووچە",
  "Full Time": "دەوامی تەواو",
  "1 Week ON / 1 Week OFF": "١ هەفتە کار / ١ هەفتە پشوو",
  "2 Weeks ON / 2 Weeks OFF": "٢ هەفتە کار / ٢ هەفتە پشوو",
  "28 Days ON / 28 Days OFF": "٢٨ ڕۆژ کار / ٢٨ ڕۆژ پشوو",
  "6 Weeks ON / 2 Weeks OFF": "٦ هەفتە کار / ٢ هەفتە پشوو",
  "Sunday–Thursday ON; Friday–Saturday OFF": "یەکشەممە تا پێنجشەممە کار؛ هەینی و شەممە پشوو",
  "Rotation pattern": "شێوازی ڕۆتا",
  "Effective date": "بەرواری جێبەجێبوون",
  "Cycle starts": "دەستپێکی خول",
  "Install standard patterns": "دامەزراندنی شێوازە ستانداردەکان",
  "Refresh standard patterns": "نوێکردنەوەی شێوازە ستانداردەکان",
  "Override date": "بەرواری گۆڕین",
  "Override status": "دۆخی گۆڕین",
  "Bulk Historical Leave": "مۆڵەتی مێژوویی بەکۆمەڵ",
  "Bulk historical leave": "مۆڵەتی مێژوویی بەکۆمەڵ",
  "Historical leave dates": "بەروارەکانی مۆڵەتی مێژوویی",
  "Enter separate dates, one per line or separated by commas.": "بەروارەکان جیاجیا بنووسە، هەر یەک لە هێڵێک یان بە کۆما جیا بکەرەوە.",
  "Upload document": "بارکردنی بەڵگە",
  "Add historical leave": "زیادکردنی مۆڵەتی مێژوویی",
  "Leave balance": "باڵانسی مۆڵەت",
  "Leave balances": "باڵانسەکانی مۆڵەت",
  "All employee leave balances": "باڵانسی مۆڵەتی هەموو کارمەندان",
  "Requested days": "ڕۆژە داواکراوەکان",
  "Request date": "بەرواری داواکاری",
  "Decision by": "بڕیار لەلایەن",
  "No leave history found.": "هیچ مێژووی مۆڵەتێک نەدۆزرایەوە.",
  "Overtime Management": "بەڕێوەبردنی کاتی زیادە",
  "Submit for approval": "ناردن بۆ پەسەندکردن",
  "All Overtime Requests": "هەموو داواکارییەکانی کاتی زیادە",
  "Justification": "پاساو",
  "Decision": "بڕیار",
  "Edit overtime": "دەستکاری کاتی زیادە",
  "Delete overtime": "سڕینەوەی کاتی زیادە",
  "Holiday Calendar": "ڕۆژژمێری پشوو",
  "Create holiday": "دروستکردنی پشوو",
  "Holiday name": "ناوی پشوو",
  "Holiday type": "جۆری پشوو",
  "Start date *": "بەرواری دەستپێک *",
  "End date *": "بەرواری کۆتایی *",
  "All eligible employees": "هەموو کارمەندانی شیاو",
  "Company holiday": "پشووی کۆمپانیا",
  "Department holiday": "پشووی بەش",
  "Location holiday": "پشووی شوێن",
  "Timesheet Management": "بەڕێوەبردنی خشتەی کات",
  "Monthly Timesheet": "خشتەی کاتی مانگانە",
  "Submitted by": "نێردراوە لەلایەن",
  "Approver": "پەسەندکەر",
  "Audited by": "پشکنراوە لەلایەن",
  "Send for audit": "ناردن بۆ پشکنین",
  "Approve timesheet": "پەسەندکردنی خشتەی کات",
  "Return for correction": "گەڕاندنەوە بۆ ڕاستکردنەوە",
  "Ready for payroll": "ئامادە بۆ مووچە",
  "Archived": "ئەرشیفکراو",
  "Google Drive Archive": "ئەرشیفی گووگڵ درایڤ",
  "Storage status": "دۆخی هەڵگرتن",
  "Connected account": "هەژماری پەیوەستکراو",
  "Archive status": "دۆخی ئەرشیف",
  "Ask TeamRota": "لە TeamRota بپرسە",
  "Ask a question...": "پرسیارێک بپرسە...",
  "Contact HR": "پەیوەندی بە HR",
  "Send": "ناردن",
  "Notifications": "ئاگادارکردنەوەکان",
  "No notifications found.": "هیچ ئاگادارکردنەوەیەک نەدۆزرایەوە.",
  "Mark as read": "نیشانکردن وەک خوێندراو",
  "Welcome back": "بەخێربێیتەوە",
  "Sign in to your account": "بچۆ ژوورەوە بۆ هەژمارەکەت",
  "Enter your email address": "ناونیشانی ئیمەیڵەکەت بنووسە",
  "Enter your password": "وشەی نهێنییەکەت بنووسە",
  "Need help? Contact your system administrator.": "یارمەتیت دەوێت؟ پەیوەندی بە بەڕێوەبەری سیستەم بکە.",
  "Change password": "گۆڕینی وشەی نهێنی",
  "Current password": "وشەی نهێنی ئێستا",
  "New password": "وشەی نهێنی نوێ",
  "Confirm new password": "دووبارەکردنەوەی وشەی نهێنی نوێ",
  "Update password": "نوێکردنەوەی وشەی نهێنی",
  "Personal information": "زانیاری کەسی",
  "Save changes": "پاشەکەوتکردنی گۆڕانکارییەکان",
  "Admin Dashboard": "داشبۆردی ئەدمین",
  "Employee Management": "بەڕێوەبردنی کارمەندان",
  "Edit employee": "دەستکاری کارمەند",
  "Delete employee": "سڕینەوەی کارمەند",
  "Reset employee password": "نوێکردنەوەی وشەی نهێنی کارمەند",
  "Primary manager": "بەڕێوەبەری سەرەکی",
  "Secondary manager": "بەڕێوەبەری دووەم",
  "Create department": "دروستکردنی بەش",
  "Email": "ئیمەیڵ",
  "Username": "ناوی بەکارهێنەر"
};

const supplementalAr: Record<string, string> = {
  "Who Is Available Today?": "من المتاح اليوم؟",
  "All employees can view today’s workforce availability without seeing confidential leave reasons.": "يمكن لجميع الموظفين عرض توافر القوى العاملة اليوم دون الاطلاع على أسباب الإجازة السرية.",
  "Total employees": "إجمالي الموظفين", "Available today": "المتاحون اليوم", "Not available": "غير متاح", "Available": "متاح", "Unavailable": "غير متاح",
  "Working – Day": "دوام نهاري", "Working - Day": "دوام نهاري", "Working": "على رأس العمل", "Weekend": "عطلة نهاية الأسبوع", "On leave": "في إجازة", "On Leave": "في إجازة",
  "Apply filter": "تطبيق التصفية", "All statuses": "جميع الحالات", "Search employee, ID, job title or department": "ابحث عن موظف أو رقم أو مسمى وظيفي أو قسم",
  "No employees match the selected filters.": "لا يوجد موظفون يطابقون عوامل التصفية المحددة.", "LIVE WORKFORCE": "القوى العاملة المباشرة",
  "ORGANIZATION CHART": "الهيكل التنظيمي", "Primary reporting": "التبعية الرئيسية", "Secondary reporting": "التبعية الثانوية", "Expand all": "توسيع الكل", "Minimize all": "تصغير الكل", "Collapse all": "طي الكل",
  "Fit to screen": "ملاءمة للشاشة", "Zoom in": "تكبير", "Zoom out": "تصغير", "Search employees": "البحث عن الموظفين", "All departments": "جميع الأقسام", "Direct reports": "المرؤوسون المباشرون",
  "Functional Manager": "المدير الوظيفي", "Department not assigned": "القسم غير محدد", "No department": "بدون قسم", "Active": "نشط", "Inactive": "غير نشط", "Open": "فتح", "Close": "إغلاق",
  "Cancel": "إلغاء", "Delete": "حذف", "Edit": "تعديل", "Update": "تحديث", "Activate": "تفعيل", "Deactivate": "تعطيل", "Search": "بحث", "Filter": "تصفية", "Clear": "مسح", "Back": "رجوع", "Next": "التالي", "Previous": "السابق", "Done": "تم",
  "Success": "نجاح", "Error": "خطأ", "Warning": "تحذير", "Loading...": "جارٍ التحميل...", "No data available.": "لا توجد بيانات متاحة.", "No records found.": "لم يتم العثور على سجلات.", "Required": "مطلوب", "Optional": "اختياري",
  "Select employee": "اختر الموظف", "Select department": "اختر القسم", "Select manager": "اختر المدير", "Select status": "اختر الحالة", "Select year": "اختر السنة", "Select month": "اختر الشهر", "From": "من", "To": "إلى",
  "Start time": "وقت البدء", "End time": "وقت الانتهاء", "Reason": "السبب", "Notes": "ملاحظات", "Description": "الوصف", "Department": "القسم", "Manager": "المدير", "Role": "الدور", "Location": "الموقع", "Today": "اليوم", "Tomorrow": "غداً",
  "This month": "هذا الشهر", "This year": "هذه السنة", "Pending": "معلق", "Approved": "موافق عليه", "Rejected": "مرفوض", "Submitted": "مُرسل", "Completed": "مكتمل", "Draft": "مسودة", "Paid": "مدفوع", "Unpaid": "غير مدفوع",
  "Full Time": "دوام كامل", "1 Week ON / 1 Week OFF": "أسبوع عمل / أسبوع راحة", "2 Weeks ON / 2 Weeks OFF": "أسبوعان عمل / أسبوعان راحة", "28 Days ON / 28 Days OFF": "28 يوماً عمل / 28 يوماً راحة", "6 Weeks ON / 2 Weeks OFF": "6 أسابيع عمل / أسبوعان راحة",
  "Sunday–Thursday ON; Friday–Saturday OFF": "العمل من الأحد إلى الخميس؛ الجمعة والسبت عطلة", "Rotation pattern": "نمط المناوبة", "Effective date": "تاريخ السريان", "Cycle starts": "بداية الدورة", "Install standard patterns": "تثبيت الأنماط القياسية", "Refresh standard patterns": "تحديث الأنماط القياسية",
  "Override date": "تاريخ التجاوز", "Override status": "حالة التجاوز", "Bulk Historical Leave": "إدخال الإجازات التاريخية بالجملة", "Bulk historical leave": "إدخال الإجازات التاريخية بالجملة", "Historical leave dates": "تواريخ الإجازات التاريخية",
  "Enter separate dates, one per line or separated by commas.": "أدخل تواريخ منفصلة، تاريخاً واحداً في كل سطر أو افصل بينها بفواصل.", "Upload document": "رفع مستند", "Add historical leave": "إضافة إجازة تاريخية", "Leave balance": "رصيد الإجازة", "Leave balances": "أرصدة الإجازات", "All employee leave balances": "أرصدة إجازات جميع الموظفين",
  "Requested days": "الأيام المطلوبة", "Request date": "تاريخ الطلب", "Decision by": "القرار بواسطة", "No leave history found.": "لم يتم العثور على سجل إجازات.", "Overtime Management": "إدارة العمل الإضافي", "Submit for approval": "إرسال للموافقة", "All Overtime Requests": "جميع طلبات العمل الإضافي", "Justification": "التبرير", "Decision": "القرار", "Edit overtime": "تعديل العمل الإضافي", "Delete overtime": "حذف العمل الإضافي",
  "Create holiday": "إنشاء عطلة", "Holiday name": "اسم العطلة", "Holiday type": "نوع العطلة", "Start date *": "تاريخ البدء *", "End date *": "تاريخ الانتهاء *", "All eligible employees": "جميع الموظفين المؤهلين", "Company holiday": "عطلة الشركة", "Department holiday": "عطلة القسم", "Location holiday": "عطلة الموقع",
  "Timesheet Management": "إدارة سجلات الدوام", "Monthly Timesheet": "سجل الدوام الشهري", "Submitted by": "مُرسل بواسطة", "Approver": "المعتمد", "Audited by": "تم التدقيق بواسطة", "Send for audit": "إرسال للتدقيق", "Approve timesheet": "اعتماد سجل الدوام", "Return for correction": "إرجاع للتصحيح", "Ready for payroll": "جاهز للرواتب", "Archived": "مؤرشف",
  "Google Drive Archive": "أرشيف Google Drive", "Storage status": "حالة التخزين", "Connected account": "الحساب المتصل", "Archive status": "حالة الأرشيف", "Ask TeamRota": "اسأل TeamRota", "Ask a question...": "اطرح سؤالاً...", "Contact HR": "اتصل بالموارد البشرية", "Send": "إرسال", "Notifications": "الإشعارات", "No notifications found.": "لم يتم العثور على إشعارات.", "Mark as read": "تحديد كمقروء",
  "Welcome back": "مرحباً بعودتك", "Sign in to your account": "سجّل الدخول إلى حسابك", "Enter your email address": "أدخل عنوان بريدك الإلكتروني", "Enter your password": "أدخل كلمة المرور", "Need help? Contact your system administrator.": "هل تحتاج إلى مساعدة؟ اتصل بمسؤول النظام.", "Change password": "تغيير كلمة المرور", "Current password": "كلمة المرور الحالية", "New password": "كلمة المرور الجديدة", "Confirm new password": "تأكيد كلمة المرور الجديدة", "Update password": "تحديث كلمة المرور", "Personal information": "المعلومات الشخصية", "Save changes": "حفظ التغييرات",
  "Admin Dashboard": "لوحة تحكم الإدارة", "Employee Management": "إدارة الموظفين", "Edit employee": "تعديل الموظف", "Delete employee": "حذف الموظف", "Reset employee password": "إعادة تعيين كلمة مرور الموظف", "Primary manager": "المدير الرئيسي", "Secondary manager": "المدير الثانوي", "Create department": "إنشاء قسم", "Email": "البريد الإلكتروني", "Username": "اسم المستخدم"
};

const supplementalUr: Record<string, string> = {
  "Who Is Available Today?": "آج کون دستیاب ہے؟", "All employees can view today’s workforce availability without seeing confidential leave reasons.": "تمام ملازمین خفیہ چھٹی کی وجوہات دیکھے بغیر آج کی افرادی قوت کی دستیابی دیکھ سکتے ہیں۔",
  "Total employees": "کل ملازمین", "Available today": "آج دستیاب", "Not available": "دستیاب نہیں", "Available": "دستیاب", "Unavailable": "دستیاب نہیں", "Working – Day": "دن کی ڈیوٹی", "Working - Day": "دن کی ڈیوٹی", "Working": "کام پر", "Weekend": "ہفتہ وار تعطیل", "On leave": "چھٹی پر", "On Leave": "چھٹی پر",
  "Apply filter": "فلٹر لگائیں", "All statuses": "تمام حالتیں", "Search employee, ID, job title or department": "ملازم، آئی ڈی، عہدہ یا محکمہ تلاش کریں", "No employees match the selected filters.": "منتخب فلٹرز سے کوئی ملازم مطابقت نہیں رکھتا۔", "LIVE WORKFORCE": "براہ راست افرادی قوت",
  "ORGANIZATION CHART": "تنظیمی چارٹ", "Primary reporting": "بنیادی رپورٹنگ", "Secondary reporting": "ثانوی رپورٹنگ", "Expand all": "سب پھیلائیں", "Minimize all": "سب کم کریں", "Collapse all": "سب سمیٹیں", "Fit to screen": "اسکرین پر فٹ کریں", "Zoom in": "بڑا کریں", "Zoom out": "چھوٹا کریں", "Search employees": "ملازمین تلاش کریں", "All departments": "تمام محکمے", "Direct reports": "براہ راست ماتحت", "Functional Manager": "فنکشنل منیجر", "Department not assigned": "محکمہ مقرر نہیں", "No department": "کوئی محکمہ نہیں",
  "Active": "فعال", "Inactive": "غیر فعال", "Open": "کھولیں", "Close": "بند کریں", "Cancel": "منسوخ کریں", "Delete": "حذف کریں", "Edit": "ترمیم", "Update": "تازہ کریں", "Activate": "فعال کریں", "Deactivate": "غیر فعال کریں", "Search": "تلاش", "Filter": "فلٹر", "Clear": "صاف کریں", "Back": "واپس", "Next": "اگلا", "Previous": "پچھلا", "Done": "مکمل", "Success": "کامیابی", "Error": "خرابی", "Warning": "تنبیہ", "Loading...": "لوڈ ہو رہا ہے...", "No data available.": "کوئی ڈیٹا دستیاب نہیں۔", "No records found.": "کوئی ریکارڈ نہیں ملا۔", "Required": "ضروری", "Optional": "اختیاری",
  "Select employee": "ملازم منتخب کریں", "Select department": "محکمہ منتخب کریں", "Select manager": "منیجر منتخب کریں", "Select status": "حالت منتخب کریں", "Select year": "سال منتخب کریں", "Select month": "مہینہ منتخب کریں", "From": "سے", "To": "تک", "Start time": "شروع کا وقت", "End time": "اختتامی وقت", "Reason": "وجہ", "Notes": "نوٹس", "Description": "تفصیل", "Department": "محکمہ", "Manager": "منیجر", "Role": "کردار", "Location": "مقام", "Today": "آج", "Tomorrow": "کل", "This month": "اس ماہ", "This year": "اس سال", "Pending": "زیر التوا", "Approved": "منظور شدہ", "Rejected": "مسترد", "Submitted": "جمع شدہ", "Completed": "مکمل", "Draft": "مسودہ", "Paid": "ادا شدہ", "Unpaid": "بلا معاوضہ",
  "Full Time": "کل وقتی", "1 Week ON / 1 Week OFF": "1 ہفتہ کام / 1 ہفتہ آرام", "2 Weeks ON / 2 Weeks OFF": "2 ہفتے کام / 2 ہفتے آرام", "28 Days ON / 28 Days OFF": "28 دن کام / 28 دن آرام", "6 Weeks ON / 2 Weeks OFF": "6 ہفتے کام / 2 ہفتے آرام", "Sunday–Thursday ON; Friday–Saturday OFF": "اتوار تا جمعرات کام؛ جمعہ اور ہفتہ چھٹی", "Rotation pattern": "روٹیشن پیٹرن", "Effective date": "موثر تاریخ", "Cycle starts": "سائیکل شروع", "Install standard patterns": "معیاری پیٹرن نصب کریں", "Refresh standard patterns": "معیاری پیٹرن تازہ کریں", "Override date": "اوور رائیڈ تاریخ", "Override status": "اوور رائیڈ حالت",
  "Bulk Historical Leave": "تاریخی چھٹیوں کا اجتماعی اندراج", "Bulk historical leave": "تاریخی چھٹیوں کا اجتماعی اندراج", "Historical leave dates": "تاریخی چھٹی کی تاریخیں", "Enter separate dates, one per line or separated by commas.": "الگ تاریخیں درج کریں، ہر سطر میں ایک یا کوما سے الگ۔", "Upload document": "دستاویز اپ لوڈ کریں", "Add historical leave": "تاریخی چھٹی شامل کریں", "Leave balance": "چھٹی کا بیلنس", "Leave balances": "چھٹیوں کے بیلنس", "All employee leave balances": "تمام ملازمین کے چھٹی بیلنس", "Requested days": "درخواست کردہ دن", "Request date": "درخواست کی تاریخ", "Decision by": "فیصلہ کرنے والا", "No leave history found.": "چھٹی کی کوئی تاریخ نہیں ملی۔",
  "Overtime Management": "اوور ٹائم انتظام", "Submit for approval": "منظوری کے لیے جمع کریں", "All Overtime Requests": "تمام اوور ٹائم درخواستیں", "Justification": "جواز", "Decision": "فیصلہ", "Edit overtime": "اوور ٹائم میں ترمیم", "Delete overtime": "اوور ٹائم حذف کریں", "Create holiday": "تعطیل بنائیں", "Holiday name": "تعطیل کا نام", "Holiday type": "تعطیل کی قسم", "Start date *": "شروع کی تاریخ *", "End date *": "اختتامی تاریخ *", "All eligible employees": "تمام اہل ملازمین", "Company holiday": "کمپنی تعطیل", "Department holiday": "محکمانہ تعطیل", "Location holiday": "مقام کی تعطیل",
  "Timesheet Management": "ٹائم شیٹ انتظام", "Monthly Timesheet": "ماہانہ ٹائم شیٹ", "Submitted by": "جمع کرنے والا", "Approver": "منظور کنندہ", "Audited by": "آڈٹ کرنے والا", "Send for audit": "آڈٹ کے لیے بھیجیں", "Approve timesheet": "ٹائم شیٹ منظور کریں", "Return for correction": "درستگی کے لیے واپس کریں", "Ready for payroll": "پے رول کے لیے تیار", "Archived": "محفوظ شدہ", "Google Drive Archive": "گوگل ڈرائیو آرکائیو", "Storage status": "اسٹوریج کی حالت", "Connected account": "منسلک اکاؤنٹ", "Archive status": "آرکائیو حالت",
  "Ask TeamRota": "TeamRota سے پوچھیں", "Ask a question...": "سوال پوچھیں...", "Contact HR": "ایچ آر سے رابطہ", "Send": "بھیجیں", "Notifications": "اطلاعات", "No notifications found.": "کوئی اطلاع نہیں ملی۔", "Mark as read": "پڑھا ہوا نشان زد کریں", "Welcome back": "خوش آمدید", "Sign in to your account": "اپنے اکاؤنٹ میں سائن ان کریں", "Enter your email address": "اپنا ای میل درج کریں", "Enter your password": "اپنا پاس ورڈ درج کریں", "Need help? Contact your system administrator.": "مدد چاہیے؟ سسٹم ایڈمن سے رابطہ کریں۔", "Change password": "پاس ورڈ تبدیل کریں", "Current password": "موجودہ پاس ورڈ", "New password": "نیا پاس ورڈ", "Confirm new password": "نئے پاس ورڈ کی تصدیق", "Update password": "پاس ورڈ اپ ڈیٹ کریں", "Personal information": "ذاتی معلومات", "Save changes": "تبدیلیاں محفوظ کریں",
  "Admin Dashboard": "ایڈمن ڈیش بورڈ", "Employee Management": "ملازمین کا انتظام", "Edit employee": "ملازم میں ترمیم", "Delete employee": "ملازم حذف کریں", "Reset employee password": "ملازم کا پاس ورڈ ری سیٹ کریں", "Primary manager": "بنیادی منیجر", "Secondary manager": "ثانوی منیجر", "Create department": "محکمہ بنائیں", "Email": "ای میل", "Username": "صارف نام"
};

Object.assign(ku, supplementalKu);
Object.assign(ar, supplementalAr);
Object.assign(ur, supplementalUr);

function translateText(text: string, dictionary: Record<string, string>) {
  const trimmed = text.trim();
  if (!trimmed) return text;
  const direct = dictionary[trimmed];
  if (direct) return text.replace(trimmed, direct);

  // Support labels that include trailing punctuation or counts, e.g. "Status:" or "Employees (13)".
  const punctuationMatch = trimmed.match(/^(.+?)([:：!?؟])$/);
  if (punctuationMatch && dictionary[punctuationMatch[1]]) {
    return text.replace(trimmed, `${dictionary[punctuationMatch[1]]}${punctuationMatch[2]}`);
  }
  const countMatch = trimmed.match(/^(.+?)\s*\((\d+)\)$/);
  if (countMatch && dictionary[countMatch[1]]) {
    return text.replace(trimmed, `${dictionary[countMatch[1]]} (${countMatch[2]})`);
  }
  return text;
}

function translateTree(root: ParentNode, dictionary: Record<string, string>) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  for (const node of nodes) {
    const parent = node.parentElement;
    if (!parent || parent.closest("script,style,textarea,[data-no-translate]")) continue;
    node.textContent = translateText(node.textContent || "", dictionary);
  }

  root.querySelectorAll<HTMLElement>("[placeholder],[title],[aria-label],[value]").forEach((el) => {
    for (const attr of ["placeholder", "title", "aria-label", "value"]) {
      const current = el.getAttribute(attr);
      if (current && dictionary[current.trim()]) el.setAttribute(attr, dictionary[current.trim()]);
    }
  });
}

export default function LanguageSwitcher() {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("teamrota-language") as Language | null;
    const selected: Language = saved === "ku" || saved === "ar" || saved === "ur" ? saved : "en";
    setLanguage(selected);

    document.documentElement.lang = selected === "ku" ? "ckb" : selected;
    document.documentElement.dir = selected === "en" ? "ltr" : "rtl";
    document.body.classList.toggle("language-ku", selected === "ku");
    document.body.classList.toggle("language-ar", selected === "ar");
    document.body.classList.toggle("language-ur", selected === "ur");

    const dictionary = selected === "ku" ? ku : selected === "ar" ? ar : selected === "ur" ? ur : null;
    if (dictionary) {
      translateTree(document.body, dictionary);
      const observer = new MutationObserver((mutations) => {
        for (const mutation of mutations) {
          mutation.addedNodes.forEach((node) => {
            if (node.nodeType === Node.ELEMENT_NODE) translateTree(node as Element, dictionary);
            if (node.nodeType === Node.TEXT_NODE && node.parentNode) translateTree(node.parentNode, dictionary);
          });
        }
      });
      observer.observe(document.body, { childList: true, subtree: true });
      return () => observer.disconnect();
    }
  }, []);

  function changeLanguage(next: Language) {
    if (next === language) return;
    localStorage.setItem("teamrota-language", next);
    window.location.reload();
  }

  return (
    <div className="language-switcher language-switcher-flags" data-no-translate aria-label="Language selector">
      <button type="button" className={language === "en" ? "active" : ""} onClick={() => changeLanguage("en")} title="English" aria-label="English">
        <img className="language-flag-image" src="/flags/uk.svg" alt="" aria-hidden="true"/>
        <span className="language-name">English</span>
      </button>
      <button type="button" className={language === "ku" ? "active" : ""} onClick={() => changeLanguage("ku")} title="Kurdish (Sorani)" aria-label="Kurdish (Sorani)">
        <img className="language-flag-image" src="/flags/krg.svg" alt="" aria-hidden="true"/>
        <span className="language-name">کوردی</span>
      </button>
      <button type="button" className={language === "ar" ? "active" : ""} onClick={() => changeLanguage("ar")} title="Arabic" aria-label="Arabic">
        <img className="language-flag-image" src="/flags/iraq.svg" alt="" aria-hidden="true"/>
        <span className="language-name">العربية</span>
      </button>
      <button type="button" className={language === "ur" ? "active" : ""} onClick={() => changeLanguage("ur")} title="Urdu" aria-label="Urdu">
        <img className="language-flag-image" src="/flags/pakistan.svg" alt="" aria-hidden="true"/>
        <span className="language-name">اردو</span>
      </button>
    </div>
  );
}
